const itemData =
{
    movingBoxes:  {
        "§": 1,
        "№": NaN,
        "Positionsname": "Umzugskartons",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.075,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    clothesBags:{
        "§": 1,
        "№": NaN,
        "Positionsname": "Taschen mit Kleidung",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.08,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    suitcase:{
        "§": 1,
        "№": NaN,
        "Positionsname": "Koffer",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.07,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    smallThings:{
        "§": 1,
        "№": NaN,
        "Positionsname": "Kleine Dinger, Taschen, Rucksäcke bis 10 kg",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 7,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.035,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.025,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 0.875,
        "Menge (€)": 0
    },
    beds:{
        bed90x200:{
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett  90×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 50,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 0.54,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.4,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 14,
            "Menge (€)": 0
        },
        bed140x200:{
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett 140×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 70,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 0.84,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.45,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 15.75,
            "Menge (€)": 0
        },
        bed180x200:{
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett 180×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 90,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 1.08,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.45,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 15.75,
            "Menge (€)": 0
        },
        {
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett/Boxspringbett  90×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 60,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 0.72,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.4,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 14,
            "Menge (€)": 0
        },
        {
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett/Boxspringbett 140×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 80,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 1.12,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.45,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 15.75,
            "Menge (€)": 0
        },
        {
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett/Boxspringbett 180×200 cm",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 100,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 1.44,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.45,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 15.75,
            "Menge (€)": 0
        },
        {
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett/Kinderbett",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 50,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 0.48,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.2,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 7,
            "Menge (€)": 0
        },
        {
            "§": 3,
            "№": NaN,
            "Positionsname": "Bett/Klappbett",
            "Menge (Stk)": 0,
            "Gewicht (kg)": 20,
            "Gesamt gewicht (kg)": 0,
            "Volumen (m³)": 0.325,
            "Gesamt (m³)": 0,
            "Arbeits stunden (h)": 0.1,
            "Gesamt zahl der Arbeits stunden (h)": 0,
            "Stückpreis (€)": 3.5,
            "Menge (€)": 0
        },
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Bild bis zu 1m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.081,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Bild bis zu 2m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.18,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.2,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 7,
        "Menge (€)": 0
    },
    {
        "§": 8,
        "№": NaN,
        "Positionsname": "Büroausstattung",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.07,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 11,
        "№": NaN,
        "Positionsname": "Fahrrad",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.16,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.6000000000000005,
        "Menge (€)": 0
    },
    {
        "§": 7,
        "№": NaN,
        "Positionsname": "Fernseher bis zu 40 Zoll",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.12,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.125,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.375,
        "Menge (€)": 0
    },
    {
        "§": 7,
        "№": NaN,
        "Positionsname": "Fernseher bis zu 60 Zoll",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 30,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.25,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.25,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 8.75,
        "Menge (€)": 0
    },
    {
        "§": 8,
        "№": NaN,
        "Positionsname": "Gamingstuhl, Bürostuhl",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.35,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 9,
        "№": NaN,
        "Positionsname": "Garderobe",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.16,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 12,
        "№": NaN,
        "Positionsname": "Gartenmöbel Sessel",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 5,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.27,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 12,
        "№": NaN,
        "Positionsname": "Gartenmöbel Tisch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.2,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 7,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Geschirrspüler",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.302,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Hochschrank Badezimmer",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.6,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 1m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.6,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 2m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.2,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 3m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 100,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.8,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Kleiderschrank/Schwebetürenschrank 2-türig",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.2,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Kleiderschrank/Schwebetürenschrank 3-türig",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 100,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.8,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Kommode, Sideboard",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.54,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Küchenabzug",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.072,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 5,
        "№": NaN,
        "Positionsname": "Küchenschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.4,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 5,
        "№": NaN,
        "Positionsname": "Küchenwandschränke",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.22,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Kühlschrank 2-türig",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 100,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.96,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.6,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 21,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Kühlschrank bis zu 1,2m hoch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 40,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Kühlschrank bis zu 2m hoch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.85,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.5,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 17.5,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Lampe, Deckenlampe",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 5,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.035,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Lampe, Stehlampe",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.16,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Lattenrost  90×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.18,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Lattenrost 140×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.28,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Lattenrost 180×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.36,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Matratz  90×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.45,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Matratz 140×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.7,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Matratz 180×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.9,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Medikamentenschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.07,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Mikrowelle",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.07,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 3,
        "№": NaN,
        "Positionsname": "Nachttisch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.22,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.05,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 1.75,
        "Menge (€)": 0
    },
    {
        "§": 6,
        "№": NaN,
        "Positionsname": "Ofen und Herd",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.3,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Pflanze bis zu 1m hoch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.16,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Pflanze bis zu 2m hoch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.4,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.2,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 7,
        "Menge (€)": 0
    },
    {
        "§": 5,
        "№": NaN,
        "Positionsname": "Platte",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 40,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.25,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 11,
        "№": NaN,
        "Positionsname": "Regale",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.6,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.18,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 6.3,
        "Menge (€)": 0
    },
    {
        "§": 8,
        "№": NaN,
        "Positionsname": "Rollcontainer",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.22,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Schlaf-/Gästesofa  90×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.28,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 8,
        "№": NaN,
        "Positionsname": "Schreibtisch leichter",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.72,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 8,
        "№": NaN,
        "Positionsname": "Schreibtisch schwerer",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.9,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 9,
        "№": NaN,
        "Positionsname": "Schuhschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.2,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Sessel",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.6,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Sofa aus 1 Teilen",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.28,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Sofa, Ecksofa aus 2 Teilen",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1.9,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Sofa, Ecksofa aus 3 Teilen",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 100,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 2.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.6,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 21,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Spiegel bis zu 1m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.081,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.125,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.375,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Spiegel bis zu 2m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.18,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.25,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 8.75,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Spiegelschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.2,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.15,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.25,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Stühle",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.097,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Teppich bis zu 1m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.09,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.1,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 3.5,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Teppich bis zu 2m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.32,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.2,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 7,
        "Menge (€)": 0
    },
    {
        "§": 2,
        "№": NaN,
        "Positionsname": "Teppich bis zu 3m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 40,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.48,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.333,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 11.655000000000001,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Tisch leichter oder Couchtisch mit Glasplatte",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.3,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Tisch leichter, Couchtisch",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 20,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.3,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Tisch schwerer",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 4,
        "№": NaN,
        "Positionsname": "Tisch schwerer mit Glasplatte",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.45,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 15.75,
        "Menge (€)": 0
    },
    {
        "§": 11,
        "№": NaN,
        "Positionsname": "Trockenmaschine",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 60,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.302,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.4,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 14,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Waschbeckenunterschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 15,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.3,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Wäschekorb",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 10,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.075,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.12,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 4.2,
        "Menge (€)": 0
    },
    {
        "§": 11,
        "№": NaN,
        "Positionsname": "Waschmaschine",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 80,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.302,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.5,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 17.5,
        "Menge (€)": 0
    },
    {
        "§": 10,
        "№": NaN,
        "Positionsname": "Waschmaschinenschrank",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 25,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0.17,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": 5.95,
        "Menge (€)": 0
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": 0,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": NaN,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": NaN,
        "Gewicht (kg)": "Arbeits stunden (h)",
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": "Arbeits stunden (h)",
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 1m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 0.5,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 2m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 0.75,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.75,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Kleiderschrank bis zu 3m breit",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 1,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 1,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Bett  90×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 0.3,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.3,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Bett 140×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 0.4,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.4,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": "Bett 180×200 cm",
        "Menge (Stk)": 0,
        "Gewicht (kg)": 0.5,
        "Gesamt gewicht (kg)": 0,
        "Volumen (m³)": 0.5,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": NaN,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": 0,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": NaN,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Etage der Altbauwohnung",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 1,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Etage der Neubauwohnung",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 1,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Entfernung vom Eingang zum LKW bei der Altbauwohnung",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 1,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Entfernung vom Eingang zum LKW bei der Neubauwohnung",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 1,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Entfernung zwischen neuer und alter Wohnung",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": 2,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": 0,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": NaN,
        "Positionsname": NaN,
        "Menge (Stk)": NaN,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Gesamtzahl ",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Gesamtgewicht ",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Gesamtvolumen",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Gesamtarbeitsstunden",
        "Positionsname": NaN,
        "Menge (Stk)": 0,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Stundenlohnpreis",
        "Positionsname": NaN,
        "Menge (Stk)": 35,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    },
    {
        "§": NaN,
        "№": "Bestellung eines Fahrzeugs für den Umzug",
        "Positionsname": NaN,
        "Menge (Stk)": 100,
        "Gewicht (kg)": NaN,
        "Gesamt gewicht (kg)": NaN,
        "Volumen (m³)": NaN,
        "Gesamt (m³)": NaN,
        "Arbeits stunden (h)": NaN,
        "Gesamt zahl der Arbeits stunden (h)": NaN,
        "Stückpreis (€)": NaN,
        "Menge (€)": NaN
    }
}